# Generated by vmake version 10.4b

# Define path to each library
LIB_IEEE = /opt/altera_lite/15.1/modelsim_ase/linuxaloem/../ieee
LIB_STD = /opt/altera_lite/15.1/modelsim_ase/linuxaloem/../std
LIB_WORK = per_template_lib
LIB_PER_TEMPLATE_LIB = per_template_lib

# Define path to each design unit
IEEE__numeric_std = $(LIB_IEEE)/_lib.qdb
IEEE__std_logic_1164 = $(LIB_IEEE)/_lib.qdb
STD__textio = $(LIB_STD)/_lib.qdb
PER_TEMPLATE_LIB__per_template_tb__testbench = $(LIB_PER_TEMPLATE_LIB)/_lib.qdb
PER_TEMPLATE_LIB__per_template_tb = $(LIB_PER_TEMPLATE_LIB)/_lib.qdb
PER_TEMPLATE_LIB__per_template_pkg = $(LIB_PER_TEMPLATE_LIB)/_lib.qdb
PER_TEMPLATE_LIB__per_template__rtl = $(LIB_PER_TEMPLATE_LIB)/_lib.qdb
PER_TEMPLATE_LIB__per_template = $(LIB_PER_TEMPLATE_LIB)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_PER_TEMPLATE_LIB)/_lib.qdb

$(LIB_PER_TEMPLATE_LIB)/_lib.qdb : ../../../rtl/peripherals/per_template/per_template_entity.vhd \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../rtl/peripherals/per_template/per_template_arch.vhd \
		$(PER_TEMPLATE_LIB__per_template) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../rtl/peripherals/per_template/per_template_pkg.vhd \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../rtl/peripherals/per_template/per_template_tb.vhd \
		$(PER_TEMPLATE_LIB__per_template_pkg) \
		$(STD__textio) \
		$(IEEE__std_logic_1164)
	$(VCOM) -work per_template_lib -2008 ../../../rtl/peripherals/per_template/per_template_entity.vhd
	$(VCOM) -work per_template_lib -2008 ../../../rtl/peripherals/per_template/per_template_arch.vhd
	$(VCOM) -work per_template_lib -2008 ../../../rtl/peripherals/per_template/per_template_pkg.vhd
	$(VCOM) -work per_template_lib -2008 ../../../rtl/peripherals/per_template/per_template_tb.vhd

